### PR TITLE
Fix banlist bug

### LINKED ISSUE #589: Banlist bug
When banning a new alt of an existing banned user, if the existing banned user has an underscore in their username, its banlist listing will break upon banning the new alt.  `example_name` becomes `example, _name`.

### PR DESCRIPTION
**Pull request by robdy**
Fixes #589 by replacing `\_` with `_` and then reverting. The actual issue is that while doing `split(/\s*\|\s*/)` backslash in username causes splitting.

Kind of workaround here but I haven't found any better solution.

### CODE REVIEW

File: api/services/Ban.js [hunk 1]
```diff
@@ -93,13 +93,13 @@ exports.updateBanlist = async function (redToken, username, banlistEntry, friend
     if (knownAlt && lines[i].includes(knownAlt) || lines[i].includes(username)
```
Comment (SnowPhoenix) [inline api/services/Ban.js]: This isn't an issue with your proposed solution, of course, but as I'm reviewing this, I'm thinking this line would still cause issues in cases where the username contains underscores since (as far as I'm aware; correct me if I'm wrong, please) the `knownAlt` variable doesn't have the underscores escaped while the `lines[i]` variable still would.

I'm wondering if perhaps it'd be better to just escape the underscores in `knownAlt` and `username` at the start of the function, and then work with those variants. What are your thoughts?

File: api/services/Ban.js [hunk 2]
```diff
@@ -93,13 +93,13 @@ exports.updateBanlist = async function (redToken, username, banlistEntry, friend
...
       // User was an alt account, modify the existing line instead of creating a new one
-      let blocks = lines[i].split(/\s*\|\s*/);
+      let blocks = lines[i].replace('\\_','_').split(/\s*\|\s*/);
       let user_regex = '(?:^|\\s)('+username+(knownAlt ? '|'+knownAlt : '')+')(?:,|$)';
       let fc_match = _.intersection(blocks[1].match(/(\d{4}-){2}\d{4}/g), friend_codes).length;
       if (blocks.length !== 5 || !(fc_match || blocks[0].match(new RegExp(user_regex)))) {
         continue;
       }
-      blocks[0] = _.union(blocks[0].match(/[\w-]{1,20}/g), [username]).join(', ');
+      blocks[0] = _.union(blocks[0].match(/[\w-]{1,20}/g), [username]).join(', ').replace('_','\\_');
```
Comment (SnowPhoenix) [inline api/services/Ban.js]: If we do stick to variables with pre-escaped underscores, we could alter this regex to be something like `/(?:[A-Za-z0-9]|\\_){1,20}/g`, but I'm wondering if we should just split `blocks[0]` into a secondary array on `/\s*,\s*/` instead.

_Ideally_ `blocks[0]` should contain nothing except for comma-separated Reddit usernames, but up until a few months ago, we did have a name entry that was in the format `IRC nick: irc_nick` in one of the banlist entries. As we've seen, unusual entries such as this can lead to unexpected results, so I'm thinking just treating whatever's separated by commas as a name might be best, without placing further restrictions on what else it has to be.

File: api/services/Ban.js (hunk 1 above)
Comment (robdy) [reply api/services/Ban.js]: I tried to do this escaping but it was somehow breaking `user_regex` and it never matched. I did it opposite way. Assuming that you dont escape underscore while using ban form I just added backslashes at the moment when `_union` is used.

**Comment by robdy** [comment]
Actually I found out that previous version works but only if you enter FC (which was what I did during the test) so I had to rebuild it a little bit.

Regarding unusual entries - if we want to support them I'd have to write regex to remove all the escaping and then add it back (or rewrite `user_regex`). Both can be challenging a bit and I'm not sure if it's worth to put such effort here.

**Comment by robdy** [comment]
Ok I got rid of `fromCharCode`as agreed on chat.
