### PR TITLE
Count bank trades for flair, fix some bugs

### LINKED ISSUE #501: Count bank trades for flair

### PR DESCRIPTION
**Pull request by not-an-aardvark**

### CODE REVIEW

File: api/controllers/HomeController.js [hunk 1]
```diff
@@ -28,7 +28,7 @@ module.exports = {
           }
         });
       }
-    });
+    }, sails.log.error);
```
Comment (not-an-aardvark) [inline api/controllers/HomeController.js]: When the user loads the index page, we refresh their flair, but only after sending a response. This was causing errors to get swallowed.

File: api/services/Ban.js [hunk 2]
```diff
@@ -87,19 +88,25 @@ exports.updateBanlist = async function (redToken, username, banlistEntry, friend
...
       let blocks = lines[i].split(' | ');
       if (blocks.length !== 4) {
         break;
       }
-      blocks[0] += ', /u/' + username;
+      blocks[0] = _.union(blocks[0].match(/\/?u\/[\w-]{1,20}/g), ['/u/' + username]).join(', ');
       blocks[1] = _.union(blocks[1].match(/(\d{4}-){2}\d{4}/g), friend_codes).join(', ');
-      blocks[3] = _.compact(_.union(blocks[3].split(', '), [igns])).join(', ');
+      try {
+        blocks[3] = Flairs.formatGames(Flairs.combineGames(Flairs.parseGames(blocks[3]), Flairs.parseGames(igns)));
```
Comment (not-an-aardvark) [inline api/services/Ban.js]: This prevents any duplicate entries from being created on the banlist. Now if two people ban someone at once, there won't be any side-effects (aside from the banned person getting two ban messages).

File: api/services/Reddit.js [hunk 3]
```diff
@@ -35,7 +35,7 @@ exports.refreshToken = async function(refreshToken) {
 };
 
 var makeRequest = async function (refreshToken, requestType, url, data, rateLimitRemainingThreshold, silenceErrors) {
-  if (left < rateLimitRemainingThreshold && moment().before(resetTime)) {
+  if (left < rateLimitRemainingThreshold && moment().isBefore(resetTime)) {
```
Comment (not-an-aardvark) [inline api/services/Reddit.js]: This would have thrown a TypeError if we had ever actually hit the ratelimit.

File: api/services/Usernotes.js [hunk 4]
```diff
@@ -16,7 +17,7 @@ exports.addUsernote = async function (redToken, modname, subreddit, user, noteTe
   var mods = parsed.constants.users;
   var warnings = parsed.constants.warnings;
   var notes = decompress(parsed.blob);
-  if (!notes.user) {
+  if (!notes[user]) {
```
Comment (not-an-aardvark) [inline api/services/Usernotes.js]: This line was causing #503. The bugged version was looking for a key matching the literal string "user", instead of a key that matched the actual username.

File: api/services/References.js [hunk 5]
```diff
@@ -8,7 +8,8 @@ exports.approve = function (ref, approve) {
       or: [
         {type: 'casual'},
         {type: 'shiny'},
-        {type: 'event'}
+        {type: 'event'},
+        {type: 'bank'}
```
Comment (not-an-aardvark) [inline api/services/References.js]: The backend still calls it "bank". We can fix this later (e.g. next update), but fixing it now is probably not a good idea since it will lead to bugs, and this particular fix isn't going through a beta-testing cycle.

File: assets/views/home/row.ejs [hunk 6]
```diff
@@ -2,9 +2,10 @@
   <strong>
     {{$index + 1}}.
   </strong>
+  <button ng-if="isBank(reference) && reference.user === user.name" class="btn btn-xs has-spinner" ng-click="moveRefToShinySection(reference)"><div title="This section used to include shinies and events from past generations, but now it only includes events. If this trade was here because it involved past-gen shinies, click here to move it up to the Shiny section instead. (This button is probably a temporary feature, since we know people will be moving a lot of things in the near future.)">Move to Shiny section</div></button>
```
Comment (not-an-aardvark) [inline assets/views/home/row.ejs]: [Demonstration](https://i.gyazo.com/760c6b251aca813752150eb76f43d4d8.gif)

File: api/services/References.js (hunk 5 above)
Comment (YaManicKill) [inline api/services/References.js]: We could probably keep it bank in the backend full-stop, because an actual change seems unnecessary. There are other things that are still called their original names. It's obvious what they actually are.

File: assets/views/home/row.ejs (hunk 6 above)
Comment (YaManicKill) [inline assets/views/home/row.ejs]: Hmmmm. Fine.
